### ISSUE TITLE
[Snapshot 20w21a] java.lang.RuntimeException: Could not execute entrypoint stage 'client'

### ISSUE THREAD

**Issue by HendrikJ79** [dexman545/Fabric-Autoswitch#10]
Crash while loading game, crash-report attached

[crash-2020-05-20_21.06.55-client.txt](https://github.com/dexman545/Fabric-Autoswitch/files/4658811/crash-2020-05-20_21.06.55-client.txt)

**Comment by dexman545** [comment]
Fixed in 2.0.1
