### ISSUE TITLE
[Snapshot 20w22a] java.lang.NoSuchMethodError: net.minecraft.class_3614.method_15805

### ISSUE THREAD

**Issue by HendrikJ79** [dexman545/Fabric-Autoswitch#12]
Game loads with AutoSwitch enabled, when trying to mine a block with incorrect tool instant chrashes

[crash-2020-05-29_19.23.25-client.txt](https://github.com/dexman545/Fabric-Autoswitch/files/4704620/crash-2020-05-29_19.23.25-client.txt)

**Comment by dexman545** [comment]
Next release will fix it, just found another bug I will be taking care of as well then it will be on curseforge.
