### ISSUE TITLE
1.9.0 crashes on load in 1.5.2 if you have modmenu installed

### ISSUE THREAD

**Issue by maxvar** [dexman545/Fabric-Autoswitch#13]
It seems that you removed menu integration classes when backporting from 1.16, but left the entrypoint for it in `fabric.mod.json`. So it throws `java.lang.ClassNotFoundException: autoswitch.modmenu.ModMenuImpl`.
I commented out the modmenu entrypoint in the jar and it fixed the problem.

**Comment by dexman545** [comment]
Fixed in 1.9.1
