### ISSUE TITLE
Ghost blocks again

### ISSUE THREAD

**Issue by DanShu15** [dexman545/Fabric-Autoswitch#15]
Got another one of these for you in case it helps :) Disabling is a perfectly acceptable work around in my opinion tho.
Got a video of it happening
https://cdn.discordapp.com/attachments/714124655597715517/720445783198924848/20200610_191308.mp4

and the console warning
https://pastebin.com/Je0HLxdK

If you want an actual log I can get that too, but I figured this was enough and it seems like you're aware that it happens. Nbd in my opinion tbh, but it was reported to me so I'm reporting it to you :)
Have a nice day and thanks for the sweet mod!

**Comment by dexman545** [comment]
Multiplayer or single player?
Which version of autoswitch are you using?

**Comment by DanShu15** [comment]
Multiplayer server using 1.15.2s latest version

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by shagone** [comment]
hey dexman545
some server use a  security that cancel your last action if you are switching tools too fast right after mining a block. 
ie: when you are using a shovel for gravel and then you are hiting somes rocks, you will switch to the pickaxe, this is normal, but if it's too fast the server will just canceling that.
you can avoid part of the bug by setting switchbackBlocks = false
but it will not solve your main problem ( i.e dirt to rock )
so I highly recommend using a delay between mining and switching tool in preference adjustable into autoswitch.cfg.

**Comment by dexman545** [comment]
Thanks for the info. I'll see about adding a delay in a few days.

**Comment by dexman545** [comment]
This will go on the backburner for a bit as it wasn't as trivial to add as I hoped (the attack block events only fire at the start of attacking the block). Had a harddrive fail, so busy fixing that stuff.

**Comment by shagone** [comment]
sure, can't wait for your update
good job and good luck

**Comment by dexman545** [comment]
[autoswitch-2.6.0-rc.3.jar.zip](https://github.com/dexman545/Fabric-Autoswitch/files/4882641/autoswitch-2.6.0-rc.3.jar.zip)
Here is a test of the delay system - let me know if it works. Hardcoded delay at this time, not functioning for switchback either.

**Comment by shagone** [comment]
sorry for the late reply, I haven't tested yet, I'm playing on a 1.15.2 server

**Comment by dexman545** [comment]
1.15 is not focused for development, features and fixes get backdated from 1.16 to 1.15.
The backdate for these features will happen in a few days.

**Comment by dexman545** [comment]
@shagone 1.12.0 should have the delays in place, though the values may need tweaking to prevent ghost blocks.

**Comment by shagone** [comment]
everything works like a charm, the default delays did the job, nice work !
I just had to update my fabric loader to the latest version ( 0.9.0 )

**Comment by dexman545** [comment]
@shagone Glad it worked for you! I'm more stringent about bumping required version for things like loader since it tends to only be updated when something important has changed, so best to keep it updated anyways.
