### ISSUE TITLE
Disabled by default option

### ISSUE THREAD

**Issue by DanShu15** [dexman545/Fabric-Autoswitch#16]
Just a feature request for a config option to disable Autoswitch at log in until someone uses the hotkey R to enable it.

**Comment by dexman545** [comment]
Added in 2.4.0

**Comment by DanShu15** [comment]
My apologies, I should've mentioned we are on 1.10 at the moment for Minecraft 1.15.2 until we can migrate our modpack and world to a more current version.
Would it be too much trouble to ask for the feature again, but for the 1.15.2 version or is it a real pain in the butt?

**Comment by dexman545** [comment]
Development is done on 1.16, then backported to 1.15 (except modmenu stuff). Internal vanilla changes make backdating annoying, but not terribly so.
Once I get a fix for #17 I'll backdate to 1.15. May do it before then depending on how long it takes to track down the bug.

**Comment by DanShu15** [comment]
yea that'll be a tricky one without some kind of automatic /reload
Ours is very low priority as it's only a QoL thing we can totally live without :)
No complaints on any wait time from us :)

**Comment by dexman545** [comment]
1.11.0 should have it. Make sure to update Fabric API.

**Comment by DanShu15** [comment]
Sweet! Good looking out on the API update too, I hadn't checked our stuff for updates again yet :)
Thank you again!
