### ISSUE TITLE
autoswitch doesn't work if you rebind your hotbar keys

### ISSUE THREAD

**Issue by DbpGaming** [dexman545/Fabric-Autoswitch#17]
mc version: 1.16-pre5
mod version: 2.4.0

if you rebind the hotbar keys to say, the numpad, or letters autoswitch stops functioning, it doesn't start working if you reset your keybinds, however if you quit to titlescreen and come back to the world it will start functioning again no matter what the binds are set to

**Comment by dexman545** [comment]
Can you give exact steps to reproduce?

**Comment by DbpGaming** [comment]
the exact steps to reproduce is to just, load a world, after being sure autoswitch is working, go into the pause menu, i rebound all of the hotbar keys to my numpad instead when it happened, hit apply, exit to the game, and it would no longer work
