### ISSUE TITLE
[bug] Lan play, scrolling toolbar on pc #2, then left clicking will scroll pc # 1's tool

### ISSUE THREAD

**Issue by systox** [dexman545/Fabric-Autoswitch#18]
Noticed while playing today that i was placing tons of wrong blocks when building a house. Friend is playing next to me and we noticed that when he scrolls his hot bar then left clicks, it also advances my hotbar by one as well. Leading to my character holding sand instead of wood for example.

**Comment by dexman545** [comment]
Fixed in 2.5.2
