### ISSUE TITLE
[suggestion]add editable tools and blocks configs

### ISSUE THREAD

**Issue by Harveykang** [dexman545/Fabric-Autoswitch#2]
i cant wright it on curseforge because i'm in China so i cant log in twitch.

**Comment by dexman545** [comment]
What exactly is the issue you're having?
Tool switching when you don't want it to, mod compatibility, or something else?

**Comment by Harveykang** [comment]
sorry for my terrible English
i mean, could you add a config file to edit what tools and what blocks the mod work with

**Comment by dexman545** [comment]
I understand that, but what is the goal of it? I have some other things planned and if those do.what you want then that would be all the better

**Comment by Harveykang** [comment]
some mods add some other tools not vanilla or shears mine sponges, pickaxes mine pistons
So if i can edit the config, that would be better

**Comment by dexman545** [comment]
https://minecraft.gamepedia.com/Breaking#Best_tools
Pickaxes do nothing different for pistons, same with shears on sponges.
For modded tools, they should be adding their tool to the corresponding [FabricToolTag](https://github.com/FabricMC/fabric/blob/1.15/fabric-mining-levels-v0/src/main/java/net/fabricmc/fabric/api/tools/FabricToolTags.java), and if they do Autoswitch should detect them. The only tool this won't work for is modded shears, as there is no tag for them.

**Comment by Harveykang** [comment]
all right, any way, thank you^^

**Comment by dexman545** [comment]
If it doesn't work with modded tools, let the mod authors know to implement FabricToolTags
A more general implementation will be done once some changes get merged into Fabric

**Comment by dexman545** [comment]
Added in 0.9.0
