### ISSUE TITLE
Still crashing when holding down left and right click

### ISSUE THREAD

**Issue by Androkai** [dexman545/Fabric-Autoswitch#21]
Thx a lot for your work on this mod.

Sadly the fix in 2.7.0 for crash on holding down left and right click doesn't seem to work, still crashing for me:
https://gist.github.com/Androkai/7b3c9bcdc504cf7c45b1d002b7af46a5

**Comment by dexman545** [comment]
Should be patched in 2.7.1
Let me know if the issue is resolved or persists.

**Comment by Androkai** [comment]
Will do as soon as it's available for download 👍
![image](https://user-images.githubusercontent.com/3952718/87879200-8f7b3200-c9e9-11ea-9beb-c297a1732828.png)

**Comment by Androkai** [comment]
Works like a charm, thx a lot!
