### ISSUE TITLE
Configure via Mod Menu

### ISSUE THREAD

**Issue by Addri** [dexman545/Fabric-Autoswitch#24]
When trying to config through the mod menu the screen is just gray and has no clickable options

**Comment by dexman545** [comment]
I take it you are on 1.16.1?
At some point during the 1.16.2 snapshots the GUI stopped being backwards compatible, and I do not know why.
The GUI was just a button to open the config folder as no proper GUI has been made at this time (#23), so being broken is not critical, even more so as I only support the most recent version of each major MC version (1.15.2, 1.14.4 is free when supporting 1.15.2, and now 1.16.2).

**Comment by HyerTheTaco** [comment]
I just got mending with my axe and now whenever I try and kill something it switches to my axe
