### ISSUE TITLE
Enchantment priority bug?

### ISSUE THREAD

**Issue by SylisMC** [dexman545/Fabric-Autoswitch#25]
I'm not sure if this is intentional but the mod favors enchantments in a way that doesn't make sense to me,
when mining fortune ores, (diamonds, emeralds, lapis, redstone, glowstone the mod prefers.....

fort-3 < eff-1 fort-1
fort-3 < mend-1 fort-1
fort-3 unb-5 < eff-1 fort-1

To me id mich rather wait an extra fraction of a second for my non-efficiant pickaxe to get 3X the diamonds then to use my faster pickaxe

**Comment by dexman545** [comment]
Set `toolEnchantmentsStack` to false in `autoswitch.cfg`.

**Comment by dexman545** [comment]
Closing. If this did not fix your issue, feel free to reopen.
