### ISSUE TITLE
[Feature Request] Implement more options from original AutoSwitch

### ISSUE THREAD

**Issue by Cicero-Interactive** [dexman545/Fabric-Autoswitch#3]
Based on the options offered by [TheBombzen's original AutoSwitch mod](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1278132-thebombzens-mods#AutoSwitch). These include:
- **Enable by default**: This option determines whether to enable AutoSwitch on new worlds and on worlds AutoSwitch hasn't been used on before.
- **Use in creative**: Use AutoSwitch when in creative mode.
- **Use on blocks**: Use AutoSwitch when digging blocks.
- **Unswitch on blocks**: Switch back to previous item after digging a block.
- **Use on mobs**: Use AutoSwitch when attacking mobs.
- **Unswitch on mobs**: Switch back to previous item after attacking a mob.

Option 1 and 2 should be simple ON/OFF toggles, while option 3-6 would have:
- Never
- Always
- Singleplayer Only
- Multiplayer Only

**Comment by dexman545** [comment]
- **Enable by default**: Not sure on:  how to implement, it's usefulness
- **Use in creative**: Implemented, will be in 0.5.0
- **Use on blocks**: Implemented, will be in 0.5.0
- **Use on mobs**: Implemented, will be in 0.5.0
- **Unswitch on mobs/blocks**: Planned, but unsure how to implement

**Comment by Cicero-Interactive** [comment]
OK, nice. Yeah, I'm not that sure on the first one too, but it may be useful to some. Unswitching on the other hand is really important, I hope you can figure it out. I'd love to help you, unfortunately I'm still not that experienced in Minecraft modding.

While I personally use AutoSwitch in both SP and MP, many consider it cheating and some Servers even ban you for using it. So it's definitely important to have this option, yeah.

**Comment by dexman545** [comment]
MP check added as it's own thing.
As for helping, a lot of the logic for AS is just java, not MC specific. Feel free to make a PR or suggest things.

**Comment by dexman545** [comment]
Version 0.6+ will have switchback.
Other options were addressed earlier. As I see no need to separate the functionality of each option by SP/MP, and no need for checking if AS has been used on a world previously, this is closed until I am convinced otherwise.
