### ISSUE TITLE
Toggle using command

### ISSUE THREAD

**Issue by Brottweiler** [dexman545/Fabric-Autoswitch#30]
Would it be possible to also provide a command to toggle the mod, besides the hotkey? Personally I want to keep hotkey toggles to a minimum and prefer using a command or config menu button to toggle mods.

The AntiGhost mod has a hotkey and a `/ghost` command you can type. Not a toggle, but still. If not, I totally understand!

**Comment by dexman545** [comment]
Antighost isn't a toggle, it's asking for the server to resend the blocks around the player.

Do you have a particular use case for preferring a command toggle over a keybinding?

It also doesn't make particular sense to expose just the toggle via a command, but to expose the feature config as well which leads to some other problems - lack of comments/explanation for what they do, and the fact that the attack and interact configs won't be exposed via command either; I already have trouble with people not realizing the mod even has configs, so exposing only a subset of them isn't the greatest.

A GUI is in the works (rendering is hard), but I had not considered adding the toggle to it as the toggle is separate from the configs.

I'm not opposed to the idea of exposing the toggle in GUI or via a command, but I'll have to think about the best way to proceed with it first.

**Comment by Brottweiler** [comment]
The reason I don't prefer hotkeys are because the more mods I use, the more hotkeys I need to manage. And eventually you'll end up with every key on your keyboard being bound to some mod and you might even run out of keys. Maybe it's not very realistic or common, but I used to struggle a few years ago where the majority of my keyboard needed a key bound to a mod.

AutoSwitch might benefit from a key because some might want to quickly be able to toggle it.

**Comment by dexman545** [comment]
Add in 3.2.0-alpha.1. A test version is here: https://modrinth.com/mod/uSdcnlts/version/jZfp6p41
