### ISSUE TITLE
switchbackAllowedFor breaks this mod

### ISSUE THREAD

**Issue by Serega007RU** [dexman545/Fabric-Autoswitch#31]
In version 3.0.0 alpha 8, if in the configuration, switchbackAllowedFor set NONE, then the mod stops working at all. There is no such problem in version 2.11.6

**Comment by dexman545** [comment]
This was fixed in 3.1.1-alpha.2

**Comment by Serega007RU** [comment]
Oh, I'm sorry, I didn't notice that a new version has been published for a long time
