### ISSUE TITLE
Autoswitch sometimes switches to "wrong' tool for the job

### ISSUE THREAD

**Issue by babrevian** [dexman545/Fabric-Autoswitch#33]
Hi, thanks for a brilliant mod. I use it a lot. The only issue is that I play a server where, when you break crops with a hoe, it replants the crops. Unfortunately with this mod, when breaking crops it either switches to another tool in your hand, or to your bare hands. It does not use the hoe. This means the crops do not auto replant. Is there a way to fix this so that only a hoe is used to break crops like wheat, potatoes, beet, carrots etc?

**Comment by dexman545** [comment]
There's a few cases you'll need to cover:
In autoswitchAttackAction.cfg, add `minecraft!farmland = ` or `minecraft!farmland = hoe` on a new line.
Then on new lines, add the block id for the various crops in the same way, eg `minecraft!wheat = hoe` for wheat.

**Comment by babrevian** [comment]
Thank you. That did the trick. It is working perfect now :-D
