### ISSUE TITLE
Can't find in config

### ISSUE THREAD

**Issue by FormSans** [dexman545/Fabric-Autoswitch#36]
Even though I am new to going into config, I will found my way. But even opening all three, I can't see where I can change how much durability is left before it switches. I even did the 'find' to search for it in all three. I am unsure if there is another config I can't see or what.

**Comment by dexman545** [comment]
There is no option for configuring the threshold, just a toggle `tryPreserveDamagedTools`. Setting that to false will remove the tool protection.

Do you have a usecase where changing the threshold would be useful?

**Comment by FormSans** [comment]
I think it could be useful. I am on a server where there is a plugin that allows you to repair a tool with a iron block. I want to change the durability before it prevents use to 1 so I am not going back as often, even if it takes a few repairs before that.

**Comment by dexman545** [comment]
I really wouldn't go below 3, as there are some cases where more than one durability is taken from a tool, and there isn't a reliable way to predict when that would occur, so even if I added a way to change the threshold, I would have to enforce a minimum of 3 to prevent the feature from breaking.
