### ISSUE TITLE
changing the toggle hotkey

### ISSUE THREAD

**Issue by sapppho** [dexman545/Fabric-Autoswitch#37]
ive seen people mention where you can change the hotkey that toggles the mod on and off- the R key is binded to a rather useful command i use every few minutes and its a pain to have to move that one since id have to retrain my hands. what file can i look into to change the keybind? also im playing in fabric 1.17.1

**Comment by dexman545** [comment]
The keybinds are set in the normal options menu (where you find the normal game controls).

**Comment by sapppho** [comment]
thanks!
