### ISSUE TITLE
[BUG] AutoSwitch and AutoSwitch toggle not working in multiplayer

### ISSUE THREAD

**Issue by Sainersoop** [dexman545/Fabric-Autoswitch#4]
When you start a new instance of minecraft and join on a server, autoswitching will be disabled.
If you press the assigned key, it will stay on "Disabled".

Known workaround:
1. Load into a singleplayer world and press the key three times till it shows "Enabled".
2. Go back on your server and press the key until it shows "Enabled".

Minecraft version:  1.15.1
Fabric version:        0.7.3+build.176
Fabric api version:  fabric-api-0.4.26+build.283-1.15
mod version:          autoswitch-0.8.0

**Comment by dexman545** [comment]
Fixed in 0.8.1
https://github.com/dexman545/Fabric-Autoswitch/releases/tag/0.8.1
