### ISSUE TITLE
How do I prevent accidentally killing villagers?

### ISSUE THREAD

**Issue by aflyingpumpkin** [dexman545/Fabric-Autoswitch#42]
I recently started using this mod and I am loving it, though when I punch a villager to move them a block I end up switching to my sword and doing a sweeping attack and end up killing them. Is there a way for me to tell autoswitch to avoid switching to sword when punching villagers?

**Comment by dexman545** [comment]
In `autoswitchAttackAction.cfg`, you should be able to disable switching for villagers by adding `minecraft!villager = ` on a new line. It is important that there is nothing after the `=` on the same line.
