### ISSUE TITLE
[Question/Suggestion] Being able to use blocks with DataValue

### ISSUE THREAD

**Issue by paulreob** [dexman545/Fabric-Autoswitch#43]
Hi, I am trying to use `note_block[instrument=bass,note=16,powered=false]= shovel` and it is not working, is it possible to use it this way, since the server I am playing has custom blocks that use noteblocks with datavalue :I

**Comment by dexman545** [comment]
Blockstates are not currently supported, and the current format won't exactly like the `=` signs everywhere.

How are you getting the blockstate info, are you just manually writing it from the F3 menu?

**Comment by paulreob** [comment]
To get the blockstate I just look at the block and press `F3+I` and get it

**Comment by dexman545** [comment]
An alpha version of this is available on Modrinth. You need to replace all `=`s within the `[]` with `+`s, eg. `minecraft!note_block[instrument+bass]`
