### ISSUE TITLE
strange tool priority when setting multiple tools with multiple enchantments

### ISSUE THREAD

**Issue by JumperCzech** [dexman545/Fabric-Autoswitch#49]
i have
minecraft!mangrove_leaves = shears,hoe;minecraft:silk_touch,hoe;minecraft:mending,hoe,sword;minecraft:mending,sword
in the config

actual autoswitch priority, when tested, is: 
silk touch hoe > mending hoe > mending sword > shears > sword

already ran into a similar issue today when trying to set beehives
minecraft!beehive = axe;minecraft:silk_touch, any;minecraft:silk_touch, 
works as expected, but when i had
minecraft!beehive = axe;minecraft:silk_touch, any;minecraft:silk_touch, axe;minecraft:efficiency, axe;minecraft:mending, axe;minecraft:unbreaking, axe
the actual priority when testing ended up being
silk touch axe > efficiency axe > mending axe > unbreaking axe > silk touch pickaxe (any tool) > axe

**Comment by dexman545** [comment]
Thanks for the report! A bit busy with IRL, so I can't provide a fix immediately (when one comes it will first be released to modrinth as an alpha).

The issue is will stacking tool enchantments - for now you can work around this bug by disabling this feature.
