### ISSUE TITLE
Switching Pickaxes when mining ores

### ISSUE THREAD

**Issue by Drakonisx** [dexman545/Fabric-Autoswitch#5]
Currently without changing any default configs the auto switcher goes directly to the leftmost pick in my hotbar even if that pick can't actually mine the ore I'm mining. If a feature could be added so that is switches to the least valuable pick you have that can still mine the thing you are trying to mine that would make the use of this mod much more convenient, as I currently move my iron pick off my hotbar when i don't need it as not to use it on stone and waste it.

**Comment by dexman545** [comment]
This is planned, currently waiting for some changes to be merged into Fabric API that will make this easier (and anything I add redundant)

**Comment by dexman545** [comment]
Added in 1.4.0, requires dumb mining level check and prefer minimum viable tool to be enabled (default).
