### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by anthonyk09** [dexman545/Fabric-Autoswitch#54]
Hello, I'm just curious on how exactly I edit the tool use files. I just want to edit what tool I use for breaking glass and I keep reading through the github, yet I can't find it. Is there a short tutorial you can post so I know what to do? Thanks!

**Comment by dexman545** [comment]
https://github.com/dexman545/Fabric-Autoswitch/wiki/Config-Details#configuration

**Comment by anthonyk09** [comment]
Am I editing the tool selections through the /autoswitch in game command or the .cfg files, and if so, how do I access those files as they don't show up as .cfg files for me, but rather .class files.

**Comment by dexman545** [comment]
The config files are in the config folder in your minecraft folder. The ingame commands are only for the features

**Comment by anthonyk09** [comment]
Gotcha, I just couldn't find them. Thank you!

**Comment by anthonyk09** [comment]
Actually one last question, if possible could I get an example how to add in something like warped/crimson nylium? I tried copying from the link you posted, but it keeps crashing.

**Comment by anthonyk09** [comment]
Awesome, thank you!
