### ISSUE TITLE
Mod cannot recover from an invalid config

### ISSUE THREAD

**Issue by EntityinArray** [dexman545/Fabric-Autoswitch#56]
Steps to reproduce:

1. Launch the game and join a world
2. Open ```autoswitchAttackAction.cfg```
3. Add a line ```block@immersive_weathering:grass_growth_replaceable = any```
4. Notice how mod stops working, trying to erase this line also doesn't work anymore
5. Run ```/autoswitch cacheSwitchResults true``` (we didn't change anything, just made the mod rewrite configs)
6. Notice how it replaced our ```block@immersive_weathering:grass_growth_replaceable = any```
with ```block@immersive_weathering = grass_growth_replaceable = any```
7. The mod won't let go of ```block@immersive_weathering = grass_growth_replaceable = any``` until you fully exit the game, save the config and launch the game again

Potential solution:
Your mod tries to "fix" an invalid config, which is a bad thing to do. It would be better if it ignored invalid configs and went with default settings instead.

**Comment by dexman545** [comment]
Something could be done to potentially make this more graceful, but for now the issue is the `:`, replace it with `!`.

Thanks for the report.
