### ISSUE TITLE
Switches to hand (blank item) on hotbar

### ISSUE THREAD

**Issue by SleepyCatten** [dexman545/Fabric-Autoswitch#57]
Version: autoswitch-6.0.2
Minecraft: 1.19.3 with latest Fabric loader

Issue: AutoSwitch changes to trying to use a hand (blank tool) instead of best tool if the tool is about to break or if no idea tool is found.

What should happen: Allow tool to break or if no ideal tool is found, remain on the manually selected one.

Edit:
In case it's relevant, I'm also using Inventory Profiles Next, but I've set it to allow tools to break. Not sure if there's an odd interaction happening between these mods.

**Comment by dexman545** [comment]
You need to disable `tryPreserveDamagedTools` (name might be off). You can do so in autoswitch.cfg or ingame via the client commands.

**Comment by SleepyCatten** [comment]
> You need to disable `tryPreserveDamagedTools` (name might be off). You can do so in autoswitch.cfg or ingame via the client commands.

Hi! Doing: "/autoswitch tryPreserveDamagedTools false" allowed tools to break, which is great 😊

It does sadly seem to conflict with the tool-replacing ability of Inventory Profiles Next, sadly, as the broken tools aren't being replaced. However, that might be more of an issue for the developer of that mod.

In terms of the other behaviour (switching to hand when an item isn't recognised as having a default tool selected), is there a setting to change the behaviour for this? (I.e., to use the selected tool perhaps or define custom settings for blocks/items from common mods?)

**Comment by dexman545** [comment]
Disable `useNoDurablityItemsWhenUnspecified`. In the config file, you'll find comments documenting the features. For mod compatibility, it is up to the mod author to ensure their blocks and items are in the correct tags. Failing that, the target configs are very dynamic and allow a lot of control. You'll find documentation for them [here](https://github.com/dexman545/Fabric-Autoswitch/wiki/Config-Details). The defaults will serve as a good example.

**Comment by SleepyCatten** [comment]
> Disable `useNoDurablityItemsWhenUnspecified`. In the config file, you'll find comments documenting the features. For mod compatibility, it is up to the mod author to ensure their blocks and items are in the correct tags. Failing that, the target configs are very dynamic and allow a lot of control. You'll find documentation for them [here](https://github.com/dexman545/Fabric-Autoswitch/wiki/Config-Details). The defaults will serve as a good example.

That's lovely! Thank you so much for your kind & helpful responses 🥰
