### ISSUE TITLE
Add an auto crystal to the mod

### ISSUE THREAD

**Issue by eLeoH** [dexman545/Fabric-Autoswitch#58]
I suggest adding the function of turning on the autocrystal in the settings.
The function includes the ability to click with an empty hand(right click) on the obsidian will automatically switch and put the crystal on it.

**Comment by dexman545** [comment]
Not sure I fully understand, but this is possible now.

In the interaction config, add `minecraft!obsidian = <id of crystal>`.

**Comment by dexman545** [comment]
If you mean to place obsidian and have crystals be placed on top automatically, that is out of scope for AS.

AS could switch to you holding the crystal when right clicking obsidian such that you place it, see my previous comment.
