### ISSUE TITLE
Pumpkin should be 'axe', not 'sword'.

### ISSUE THREAD

**Issue by Moleculor** [dexman545/Fabric-Autoswitch#6]
According to the wiki, a pumpkin is best broken with an axe, not a sword.

https://minecraft.gamepedia.com/Pumpkin

It's also a noticeable speed difference in game.

You may also want to double check your other settings, just to be sure?

To be clear, it looks like deleting 'pumpkin' from swordTargetMaterials= in autoswitchMaterials.cfg fixes the issue.

**Comment by dexman545** [comment]
Fixed in 0.11.2

Swords are also the proper tool for pumpkins (see https://minecraft.gamepedia.com/Breaking#Best_tools).
I have changed the default tool order to prioritize axes over swords.

**Comment by dexman545** [comment]
It's not an error on the wiki page, unless something has changed as other places also site it -https://minecraft.gamepedia.com/Sword#Sword_breaking_times
While it's not the *best* tool for breaking pumpkins, it does provide some benefit - hence AS targeting it for swords.

**Comment by Moleculor** [comment]
The chart on the best tools section for breaking blocks is specifically for the fastest tool to break the block.

If a sword isn't the fastest tool (and it isn't, I tested it in game), then pumpkin should not be listed next to it. 

Your first link had bad info as wikis tend to do, your second link only states that an axe is the fastest option, nothing more.

Unless I'm misunderstanding some other reason why anyone would use a sword, the axe is always and significantly the better option for pumpkins.

**Comment by dexman545** [comment]
jack o lantern should also be removed.I was referring to this in the second link:
![image](https://user-images.githubusercontent.com/4873274/72582838-1839d980-38b2-11ea-87d6-49c01e063ca2.png)
Swords do *something* for them, just not a lot.

**Comment by Moleculor** [comment]
Yes, there on the right side of the chart it lists 'axe' and a 2x-8x speed increase over a sword. What the sword does is it doesn't work as slow as a fist. So it's a subpar alternative (but still an alternative), but even a diamond sword is still slower than a wood axe, if those numbers are accurate. 

Someone confused that list as a 'fastest options' list and just put all those blocks down on the fastest options chart on the other page. Of all those blocks, the majority have a better tool option. The one exception is cobwebs (same speed, different drop).
