### ISSUE TITLE
Fabric 1.20.1

### ISSUE THREAD

**Issue by herdir** [dexman545/Fabric-Autoswitch#61]
After launching fabric-loader-1.20.1 i get the error :
```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'autoswitch'!
```
using autoswitch-6.0.2

[crash-2023-06-21_18.36.16-client.txt](https://github.com/dexman545/Fabric-Autoswitch/files/11820968/crash-2023-06-21_18.36.16-client.txt)

**Comment by dexman545** [comment]
You need to use AS 7 for MC 1.20+. Alpha builds are available on Modrinth, it will be some time before it goes to CF.
