### ISSUE TITLE
AutoSwitch prefers swords over axes when mining melons and pumpkins

### ISSUE THREAD

**Issue by RisPNG** [dexman545/Fabric-Autoswitch#62]
Read title. Additionally, I haven't tested it with other blocks. I'll let you know as I play.

**Comment by dexman545** [comment]
Version?

**Comment by RisPNG** [comment]
> Version?

autoswitch-7.0.1-beta.1.jar and I'm on Minecraft 1.20.1

I'm on default config.

**Comment by dexman545** [comment]
Please try beta.2, thanks for the report.
