### ISSUE TITLE
[Feature request] Switch delay

### ISSUE THREAD

**Issue by Art0sh** [dexman545/Fabric-Autoswitch#64]
So I'm using this mod on a server where I really have problems using the mod because it switches "too fast".
Blocks glitch break and wont break until i release the mouse and manually choose the right tool to break a block.
Since I guess that this happens because it switches too fast and maybe uses axe and shovel at the same time, the server denies the action.
Or it sends too many actions/packets, I dont know and am just guessing. Thats why I'd like to request a (configurable?) delay for switching, to prevent like 20 switches in a single second.

I'm playing on 1.20, using AutoSwitch 7.0.2 with Fabric 0.83.0+1.20

**Comment by dexman545** [comment]
This is already available in autoswitch.cfg, or ingame via /autoswitch
