### ISSUE TITLE
Axe melee hits "corrected" to swords

### ISSUE THREAD

**Issue by quat1024** [dexman545/Fabric-Autoswitch#7]
Both of these are valid weapons in different situations and I don't appreciate AutoSwitch thinking it knows better.

0.11.3 part of All of Fabric 2.

**Comment by dexman545** [comment]
Axes do more damage.
If you prefer swords, simply place them at a higher priority than axes in the config.

**Comment by quat1024** [comment]
They're useful in different situations. I wouldn't carry a sword if I
wanted to only use an axe.

Nice to know there's a config but it should really stay out of making these
decisions by default, it's very confusing

**Comment by dexman545** [comment]
You can also disable switching for attacking mobs.
