### ISSUE TITLE
8.0.1版本不支持1.20.1，会显示游戏版本不符合

### ISSUE THREAD

**Issue by SCCYsccy** [dexman545/Fabric-Autoswitch#70]
1.20.1不支持8.0.1（https://www.curseforge.com/minecraft/mc-mods/fabric-autoswitch/files/5250445）文件，显示版本不符合。
从PCL的“下载”页面搜索此MOD会显示8.0.1的版本，但是如果你是从“版本设置->Mod管理->自动切换工具->详情（右侧图标按钮）”进入，就不会显示8.0.1版本的文件（Plain Craft Launcher 2启动器，https://afdian.net/a/LTCat）

**Comment by dexman545** [comment]
I've updated curseforge for the correct version information. You'll want AS 7.0.2 for MC 1.20.1.

**Comment by SCCYsccy** [comment]
curseforge上已经没有错误的版本信息了，感谢你！
