### ISSUE TITLE
Doesnt take pickaxe varient in to concinderation

### ISSUE THREAD

**Issue by Squiddy-79** [dexman545/Fabric-Autoswitch#71]
When i try to mine obsidian, it autoswitches to an iron pickaxe instead of diamond, no matter where in the hotbar it is.

**Comment by dexman545** [comment]
What versions for MC and autoswitch are you using?

**Comment by Squiddy-79** [comment]
Im on 1.21.1 with the 9.1.1

**Comment by dexman545** [comment]
Thanks for the report, sorry for the delay. Fixed in 9.1.2/10.0.0
