### ISSUE TITLE
Tool wont select Shears

### ISSUE THREAD

**Issue by Katables** [dexman545/Fabric-Autoswitch#72]
Autoswitch v9.1.1
will not auto switch to Shears when mining Wool or Leaves. 
Sometimes it will switch to Hoe to harvest Leaves.
Will not switch to Shears for Wool.

**Comment by dexman545** [comment]
Are your shears almost broken? I cannot reproduce this issue.

**Comment by Katables** [comment]
Your right, my bad its gotta be a conflict with Purpur Servers / Plugins on the server im on. Testing it in a vanilla Creative/Survival world it switched just fine.
