### ISSUE TITLE
Possible updates for Minecraft version 1.21.4?

### ISSUE THREAD

**Issue by BrockBoB** [dexman545/Fabric-Autoswitch#75]
Hello, is it possible to have a version of the mod for 1.21.4? Your mod is the best one at autoswitching tools and I really miss it.

Thank you :)

**Comment by dexman545** [comment]
I believe AS 10 already works on 1.21.4.

Glad you like it!

**Comment by BrockBoB** [comment]
Oh you are right it works perfectly, thanks again.
