### ISSUE TITLE
Bad target and ghost block

### ISSUE THREAD

**Issue by dts77** [dexman545/Fabric-Autoswitch#9]
Hello,

First of all thanks this mod it does a good job.
Bad target : 
With zombies and other mobs the mod switch to the axe to fight.
Ghost block : 
When I use a shovel (not selected) on dirt or sand it switch very fast and dig too fast for the realm. So there is ghost block very very frequently. If I select the shovel to avoid switching I have less ghost block.

Thanks for your help

**Comment by dexman545** [comment]
Recent versions should prefer swords over axes, if not you can change the priority order to make swords higher.
Some users find disabling switchback for blocks to fix the ghost block issue.
